#!/bin/bash
# 
# Shell script to check for people who are currently at the hackzogtum coburg
# hackerspace.
# 
# Install as cronjob
# */5 * * * * /path/to/file --update
#

TMPFILE=/tmp/hackzogtum
COUNTFILE=/home/jus/.hackzog-count

if [ ! -e "$TMPFILE" ] ; then
    touch "$TMPFILE"
fi

DATA=$(curl http://in.hackzogtum-coburg.de/list.php 2>/dev/null )
CONNECTED=$( echo "$DATA" | sed -r "s/<br>/\n/g"  )
NUM=$(echo "$CONNECTED" | wc -l)
LAST=$(cat $TMPFILE)
TIME=$(date +%s)

echo "$TIME $NUM" >> $COUNTFILE 

if [[ -z "$CONNECTED" ]]
then
    MESSAGE="Nobody there ..."
else
    MESSAGE="$NUM online
$CONNECTED"
fi


if [[ "$1" == "--update" || "$1" == "--update-diff" ]] 
then

    if  [[ "$LAST" == "$MESSAGE" ]]
    then
        exit
    fi
    DIFF=$( diff -u <( echo "$LAST" ) <( echo "$MESSAGE" ) | tail -n +4 )
    DISPLAY=:0 notify-send "in.hackzogtum\n$DIFF"

else

    echo "$MESSAGE"

fi

if [[ "$LAST" != "$MESSAGE" ]]
then
    echo "$MESSAGE" > $TMPFILE
fi
