#!/bin/bash
#
# Use tmux to control multiple ssh servers at once
#

if [ "$#" == "0" ]
then
    echo "Usage: multissh host1 host2 host3"
    exit
fi

sessionid=$(echo "$*" | md5sum -t | cut -d' ' -f 1)
tmux new-session -d -s $sessionid

for i in $*
do
    tmux splitw "ssh $i"
done

tmux select-pane -t 0
tmux kill-pane

tmux select-layout even-vertical
tmux set-window-option synchronize-panes on
tmux bind-key y set-window-option synchronize-panes

tmux attach-session -t $sessionid
