#!/bin/bash

# Fetch repo and app details
url=`git config --get remote.origin.url`

re="^(https|git)(:\/\/|@)([^\/:]+)[\/:]([^\/:]+)\/(.+).git$"
if [[ $url =~ $re ]]; then
    USER=${BASH_REMATCH[4]}
    REPO=${BASH_REMATCH[5]}
fi

APPINFO_VERSION=`cat appinfo/info.xml | grep -oPm1 "(?<=<version>)[^<]+"`
APPINFO_APPID=`cat appinfo/info.xml | grep -oPm1 "(?<=<id>)[^<]+"`

# Sanity checks

git fetch
git tag -l | grep $APPINFO_VERSION && echo 'Version tag already exists' && exit 1

echo "Preparing release for $APPINFO_APPID from github:$USER/$REPO as $APPINFO_VERSION"

# Building the app store release
if [ -f "krankerl.toml" ]; then
	krankerl package
fi
ARTEFACT=./build/artifacts/$APPINFO_APPID.tar.gz

# Publish
read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	echo 'Tagging release'
	github-release release -u $USER -r $REPO -t v$APPINFO_VERSION
	echo 'Tagging release'
	github-release upload -u $USER -r $REPO -t v$APPINFO_VERSION -n $APPINFO_APPID.tar.gz -f $ARTEFACT
	echo 'Publishing to the app store'
	krankerl publish https://github.com/$USER/$REPO/releases/download/v$APPINFO_VERSION/$APPINFO_APPID.tar.gz
fi
